name: RankManager
version: 1.0
api-version: 1.19
main: fr.program.Main
commands:
  create:
    description: Création d'un rang
    permission: rm.create
  remove:
    description: Supprime un rang
    permission: rm.remove
  list:
    description: Liste tout les rangs
    permission: rm.list
  spr:
    description: Donne un rang à un joueur
    permission: rm.spr
  rpr:
    description: Retire le rang d'un joueur
    permission: rm.rpr
  scr:
    description: Donne une nouvelle couleur à un rang
    permission: rm.scr
  snr:
    description: Change le nom d'un rang
    permission: rm.snr
  addperm:
    description: Donne une permission à un rang
    permission: rm.addperm
  removeperm:
    description: Retire une permission à un rang
    permission: rm.removeperm