name: RankManager
version: 1.0
api-version: 1.19
main: fr.program.Main
commands:
  create:
    description: Création d'un rang
    permission: rm.create
  list:
    description: Liste tout les rangs
    permission: rm.list
  spr:
    description: Donne un rang à un joueur
    permission: rm.spr
  scr:
    description: Donne une nouvelle couleur à un rang
    permission: rm.scr
  snr:
    description: Donne une nouvelle couleur à un rang
    permission: rm.snr